Vagrant.configure('2') do |config|
  config.vm.box = 'mifosx-15.03-debian-8.1.0-amd64'
  config.vm.box_url = 'mifosx-15.03-debian-8.1.0-amd64.box'
  config.vm.network :private_network, ip: "192.168.33.11"
  config.ssh.username = "vagrant"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 3092, "--cpus", 2, "--name", "MifosX Devbox"]
    v.gui = true
  end
end
